#!/bin/sh

set -e
dir="`pwd`"

find $dir  \
    -path "$dir/arch/*" ! -path "$dir/arch/x86*" -prune -o \
    -path "$dir/include/arch/*" ! -path "$dir/include/arch/x86*" -prune -o \
    -name "*.[chxsS]" -print > cscope.files
cscope -bkq
